// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLnV_WgFx-p7xqmX0tbvL2_91k72W1Ekc',
    appId: '1:149188286600:android:0282559bc166071184273d',
    messagingSenderId: '149188286600',
    projectId: 'tamim-456104',
    storageBucket: 'tamim-456104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkCbfha8S_SVZqG5McX6GUzqy7vx2A15Q',
    appId: '1:149188286600:ios:793f0e35557a83d484273d',
    messagingSenderId: '149188286600',
    projectId: 'tamim-456104',
    storageBucket: 'tamim-456104.firebasestorage.app',
    androidClientId: '149188286600-6p9odqq2lp2l8uhgo1altq8ngr9vrlgh.apps.googleusercontent.com',
    iosClientId: '149188286600-2f57i7gs1e3u97fp592t6fi5c08tp7jq.apps.googleusercontent.com',
    iosBundleId: 'com.hun.tamim',
  );

}